Import('env', 'envCython', 'common')

cc_sources = [
  "helpers/ekf_load.cc",
  "helpers/ekf_sym.cc",
]
libs = ["dl"]
if common != "":
  # for SWAGLOG support
  libs += [common, 'zmq']

ekf_objects = env.SharedObject(cc_sources)
rednose = env.Library("helpers/ekf_sym", ekf_objects, LIBS=libs)
rednose_python = envCython.SharedLibrary("helpers/_ekf_sym_module.so", ["helpers/ekf_sym_module.cc", ekf_objects],
                                   LIBS=libs + envCython["LIBS"], SHLIBPREFIX="", CPPPATH=envCython["CPPPATH"] + [Dir('.').abspath])

Export('rednose', 'rednose_python')
