Import('env', 'envCython', 'common')

cc_sources = [
  "helpers/ekf_load.cc",
  "helpers/ekf_sym.cc",
]
libs = []
if common != "":
  # for SWAGLOG support
  libs = ['zmq', common]

ekf_objects = env.SharedObject(cc_sources)
rednose = env.SharedLibrary("helpers/ekf_sym", ekf_objects, LIBS=libs)
rednose_python = envCython.Program("helpers/ekf_sym_pyx.so", ["helpers/ekf_sym_pyx.pyx", ekf_objects],
                                   LIBS=libs + envCython["LIBS"])

Export('rednose', 'rednose_python')
