Import('env')

gen_dir = Dir('generated/').abspath

env.RednoseCompileFilter(
  target="live",
  filter_gen_script="live_kf.py",
  output_dir=gen_dir,
)
env.RednoseCompileFilter(
  target="kinematic",
  filter_gen_script="kinematic_kf.py",
  output_dir=gen_dir,
)
env.RednoseCompileFilter(
  target="compare",
  filter_gen_script="test_compare.py",
  output_dir=gen_dir,
)
env.RednoseCompileFilter(
  target="pos_computer_4",
  filter_gen_script="lst_sq_computer.py",
  output_dir=gen_dir,
)
env.RednoseCompileFilter(
  target="pos_computer_5",
  filter_gen_script="lst_sq_computer.py",
  output_dir=gen_dir,
)
env.RednoseCompileFilter(
  target="feature_handler_5",
  filter_gen_script="feature_handler.py",
  output_dir=gen_dir,
)