name: wheels

on: [push, pull_request]

jobs:
  wheels:
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: true
      matrix:
        platform: [ {os: "ubuntu-latest", target: "manylinux_x86_64",  arch: "x86_64"},
                    {os: "ubuntu-latest", target: "manylinux_aarch64", arch: "aarch64"},
                    {os: "macos-14",      target: "macosx_arm64"       arch: "arm64"}]
        python:   [ {cp: "cp311", py: "3.11"}, {cp: "cp312", py: "3.12"}]

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      if: runner.os == 'Linux'
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all

    - name: Building wheel
      uses: pypa/cibuildwheel@v2.19.2
      env:
        CIBW_BUILD: "${{ matrix.python.cp }}-${{ matrix.platform.target }}"
        CIBW_ARCHS: "${{ matrix.platform.arch }}"
        CIBW_BEFORE_ALL_LINUX: "dnf install -y clang libffi-devel eigen3-devel python${{ matrix.python.py }}-devel"
        CIBW_BEFORE_ALL_MACOS: "brew install eigen && brew install --cask gcc-arm-embedded && brew install gcc@13"
