name: wheels

on: [push, pull_request]

jobs:
  wheels:
    runs-on: ${{ matrix.platform[0] }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - [ubuntu-latest, manylinux_aarch64]
          #- [ubuntu-latest, manylinux_x86_64]
        python: ['cp311', 'cp312']

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      if: runner.os == 'Linux'
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all

    - name: Building wheel
      uses: pypa/cibuildwheel@v2.19.2
      env:
        CIBW_BUILD: "${{ matrix.python }}-${{ matrix.platform[1] }}"
        #CIBW_MANYLINUX_X86_64_IMAGE: "manylinux_2_28"
        CIBW_MANYLINUX_AARCH64_IMAGE: "manylinux_2_28"
        CIBW_ARCHS_LINUX: "aarch64"
        CIBW_BEFORE_ALL_LINUX: "dnf install -y clang libffi-devel eigen3-devel python3.11-devel.aarch64"
